# SYSTEM
url: "https://kn1cht.github.io"
baseurl: /doctor-funding-calendar
lang: ja

# SITE
title: Doctoral Students Funding Calendar

description: >-
  Doctoral Students Funding Calendar helps you to find the best funding progam for you.

message1: >-
  本サイトは、博士課程の学生を対象とした主な生活費・研究費の支援プログラムの概要をまとめたものです。
  各プログラムの情報は、公式のWebサイトや要項を参考にできる限り正確を期しますが、<b>実際に応募を検討される際には公式の情報をよくご確認ください</b>。

keywords: >-
  Doctoral Students Funding Calendar,
  academic, research, technology,

copyright: |-
  Copyright (C)
  <a href="https://github.com/hci-calendar/hci-calendar.github.io" target="_blank" rel="noopener noreferrer">
  HCI Calendar</a>,
  <a href="https://www.github.com/kn1cht/doctor-funding-calendar" target="_blank" rel="noopener noreferrer">
  Doctoral Students Funding Calendar</a>. All rights reserved.

# INCLUDE PAGES
include: ['_pages']

sass:
  sass_dir: ./_sass
