# SYSTEM
url: "https://hci-calendar.github.io"

baseurl: ""

# SITE
title: HCI Calendar

description: >-
  Calendar of submission deadlines and conference dates for HCI and related conferences

message1: >-
  Please check corrent information on the conference website.

message2: >-
  This site provides last dates posted on our database.<br/>
  You can help us to edit on <a href="https://github.com/hci-calendar/hci-calendar.github.io">GitHub</a>
  or post on <a href="#">Google Form</a>.

keywords: >-
  HCI Calendar,
  academic, research, technology, computer science,
  HCI, Human Computer Interaction,
  VR, Virtual Reality
  CG, Computer graphics

copyright: "Copyright (C) HCI Calendar. All rights reserved."

# INCLUDE PAGES
include: ['_pages']

# EXCLUDE GEMFILE
exclude: ['Gemfile', 'Gemfile.lock', 'vendor', 'docs']

plugins:
  - jekyll-redirect-from
